## Sorting data

In [40]:
import pandas as pd

# set the row index by name
data = pd.read_csv('Data/sales.csv', index_col='State')

In [41]:
# sort default
data.sort_values(by='Sales')

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
Nevada,126.0,Green Tea,17.0,Small Market,-354.0,West,93,Tea,1419.0,Regular
Nevada,124.0,Green Tea,18.0,Small Market,-524.0,West,100,Tea,3742.0,Regular
Nevada,133.0,Green Tea,18.0,Small Market,-380.0,West,100,Tea,3742.0,Regular
Nevada,132.0,Green Tea,19.0,Small Market,-552.0,West,93,Tea,1419.0,Regular
Nevada,147.0,Green Tea,19.0,Small Market,-430.0,West,114,Tea,6413.0,Regular
...,...,...,...,...,...,...,...,...,...,...
California,178.0,Columbian,910.0,Major Market,368.0,West,127,Coffee,2617.0,Regular
New York,178.0,Columbian,912.0,Major Market,370.0,East,127,Coffee,2654.0,Regular
California,178.0,Columbian,912.0,Major Market,370.0,West,127,Coffee,2654.0,Regular
Colorado,54.0,Decaf Espresso,NaN,Major Market,80.0,Central,23,Espresso,541.0,Decaf
Colorado,71.0,Chamomile,NaN,Major Market,99.0,Central,47,Herbal Tea,1073.0,Decaf

In [42]:
# sort multiple column
data.sort_values(by=['Sales', 'Profit'], ascending=False)

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,178.0,Columbian,912.0,Major Market,370.0,West,127,Coffee,2654.0,Regular
New York,178.0,Columbian,912.0,Major Market,370.0,East,127,Coffee,2654.0,Regular
California,178.0,Columbian,910.0,Major Market,368.0,West,127,Coffee,2617.0,Regular
New York,178.0,Columbian,910.0,Major Market,368.0,East,127,Coffee,2617.0,Regular
California,166.0,Columbian,904.0,Major Market,511.0,West,127,Coffee,2654.0,Regular
...,...,...,...,...,...,...,...,...,...,...
Nevada,133.0,Green Tea,18.0,Small Market,-380.0,West,100,Tea,3742.0,Regular
Nevada,124.0,Green Tea,18.0,Small Market,-524.0,West,100,Tea,3742.0,Regular
Nevada,126.0,Green Tea,17.0,Small Market,-354.0,West,93,Tea,1419.0,Regular
Colorado,71.0,Chamomile,NaN,Major Market,99.0,Central,47,Herbal Tea,1073.0,Decaf
Colorado,54.0,Decaf Espresso,NaN,Major Market,80.0,Central,23,Espresso,541.0,Decaf

In [43]:
data['Market'].sort_index(ascending=False)

State
Wisconsin     Central
Wisconsin     Central
Wisconsin     Central
Wisconsin     Central
Wisconsin     Central
               ...
California       West
California       West
California       West
California       West
California       West
Name: Market, Length: 4241, dtype: object